#!/usr/bin/env bash

set -e ### exit if occured error

PACKAGE=wayland

. scripts/env.sh

run_clone git://anongit.freedesktop.org/wayland/wayland -b 1.3

cd_package

run_autogen

run_make
run_make install

package_success

