#!/usr/bin/env bash

set -e ### exit if occured error

PACKAGE=proto

. scripts/env.sh

run_clone git://anongit.freedesktop.org/xcb/proto

cd_package

run_autogen

run_make
run_make install

package_success

