#!/usr/bin/env bash

set -e ### exit if occured error

PACKAGE=weston

. scripts/env.sh

run_clone git://anongit.freedesktop.org/wayland/weston -b 1.3

cd_package

run_autogen \
 --disable-setuid-install

run_make
run_make install

package_success

