#!/usr/bin/env bash

set -e ### exit if occured error

. scripts/env.sh

sudo apt-get install git libtool

# dependencies for libwayland:
sudo apt-get install doxygen # or use --disable-documentation

# dependencies for Mesa:
# "sudo apt-get build-dep mesa" will install these, but will also
# install unwanted items, such as wayland itself, and xcb prototypes
# that are too old.
sudo apt-get install autoconf automake bison debhelper dpkg-dev flex \
  libexpat1-dev libudev-dev libx11-dev libx11-xcb-dev \
  libxdamage-dev libxext-dev libxfixes-dev libxxf86vm-dev \
  linux-libc-dev pkg-config python-libxml2 quilt x11proto-dri2-dev \
  x11proto-gl-dev xutils-dev

# Mesa required llvm-3.3, but newer versions are available.
# "apt-cache search 'llvm-[0-9.]*-dev'" will list them
sudo apt-get install llvm-3.3-dev
#sudo ln -sf llvm-config-3.1 /usr/bin/llvm-config

sudo apt-get install libpciaccess-dev # needed by drm

# libinput dependencies:
# libinput is needed by weston 1.5 or newer version
#sudo apt-get install libmtdev-dev libpam0g-dev

# Weston dependencies:
sudo apt-get install libxcursor-dev libjpeg-dev libpng-dev libmtdev-dev libpam-dev

